# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "IRISH COMPUTATIONAL BIOLOGY AND GENOMICS SYMPOSIUM"
email: "icbg@nuigalway.ie"
description: "Systems Genomics Summit is a student-led genomics conference scheduled for February 2022 in Galway, Ireland. We are looking forward to hosting world-class speakers working on research covering different areas in genomics and systems biology. We will have talks covering a wide range of themes, including Methods Development and Systems Biology, Metagenomics and Agrigenomics, Evolution and Population Genomics, and Health and Disease Genomics. In previous years, this conference was hosted at University College Dublin (online in 2020!) as the Computational Genomics and Molecular/Systems Biology Summit."
baseurl: "/zeppelin"
url: "http://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "CRT Genomics Data Science"
organizerAlternateName: "SFI Centre for Research Training in Genomics Data Science"
organizerDescription: "Systems Genomics Summit is a student-led genomics conference scheduled for February 2022."
organizerEmail: "icbg@nuigalway.ie"
organizerLogo: "/img/seo/logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "genomics, genetics, bioinformatics, data science, ireland, research, systems, biology, biotech, ireland, galway"
twitterAccount: "@SysGenSummit"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/registration/", text: "Registration"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/decorum/", text: "Decorum"}


# Hero Block
heroImage: "sysgen.jpg"
heroTitle: "IRISH COMPUTATIONAL BIOLOGY AND GENOMICS SYMPOSIUM"
eventDate: "1-2 December 2022"
typeoutTextValues: '"IRISH COMPUTATIONAL BIOLOGY AND GENOMICS SYMPOSIUM"'
typeoutFallback: "ICBG 2022"

# About Block
aboutTitle: "About ICBG  2022"
aboutBlock:
 - {title: "Student-led", image: "student2.jpg", text: "The format, speakers, and all activities for the symposium have been carefully selected by the SFI CRT in Genomics Data Science students." }
 - {title: "Themes", image: "cells2.jpg", text: " - Genomics of Disease and Precision Medicine <br> - Microbial Genomics for Health and Industry <br> - Accessibility in Bioinformatics <br> - Modelling Biological Systems <br> - Agriculture and Population Genomics <br> - Seisiún Gaeilge (Irish Session)" }
 - {title: "Format", image: "workshop.jpg", text: "The symposium talks will be categorized based on the 6 themes. We will have keynote speaker talks, poster session, and sponsor talks." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "attendees", detail: "from everywhere around the globe"}
 - {count: "10", specialCharacter: "", info: "speakers", detail: "from various research backgrounds"}
 - {count: "4", specialCharacter: "", info: "themes", detail: "of different aspect of genomics"}
 - {count: "0", specialCharacter: "€", info: "fees", detail: "to enter"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Keynote Speakers"
rockstarSpeakersButtonText: "Find out more about our speakers"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "hbb1.png"
venueSmallImage1: "hbb2_r.jpg"
venueSmallImage2: "hbb3.jpg"
venueSmallImage3: "hbb4.jpg"
venueTitle: "NUI Galway Human Biology Building"
venueFeatures: ['<a href="https://www.google.com/maps?q=human+biology+building+nuig&rlz=1C1GCEU_enIE969IE969&um=1&ie=UTF-8&sa=X&ved=2ahUKEwjB__iFweb3AhWbEMAKHfThC5YQ_AUoAnoECAIQBA" style="color:white">Click this to view direction</a>.']

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tweet @ us!"
twitterHashTag: "ICBG2022"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
#Update later for now replace with coming soon



# Footer
socialLinks:
 - {link: "https://twitter.com/SysGenSummit", icon: "twitter"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://genomicsdatascience.ie/", text: "SFI Genomics CRT"}
 -
  title: "Decorum"
  links:
   - {permalink: "/decorum/", text: "Code of Conduct"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:sysgensummit2021@nuigalway.ie", text: "icbg@nuigalway.ie"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Systems Genomics Summit 2022 is organized by a committee of PhD students from five Irish universities (NUIG, RCSI, TCD, UCC and UCD). We are supported by the PhD programs in SFI Center for Research Training in Genomics Data Science. We look forward to welcoming you to a fantastic event in-person this December! We are John F O’Grady (UCD), Aideen McCabee (UCC), Karen Guerrero Vázquez (NUIG), Muhammad Ali (RCSI), Catherine Higgins (UCD), Kevin Ryan (NUIG), Narod Kebabcı (UCD), Muhammad Zainul Arifin (UCD), and Micheál Ó Dálaigh  (NUIG)."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "Galway1.jpg"
directionDetailsTitle: "Get to Galway"
directionDetailsCards:
 - {title: "From the Airport", information: 'You can use either train or bus to reach Galway from Dublin Airport. More information is available at this <a href="https://www.tripsavvy.com/how-to-get-from-dublin-to-galway-4799818">site</a>.'}
 - {title: "Public Transit", information: 'Public busses are available in Galway. To find your way to the NUI Galway Human Biology Building, visit this <a href="https://www.google.com/maps/place/The+Human+Biology+Building/@53.2766449,-9.0614814,15z/data=!4m5!3m4!1s0x485b96f17ec4e985:0xc9d0744e751e6211!8m2!3d53.2785951!4d-9.0591318">map</a>.'}
 - {title: "Hotels", information: 'Galway has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Hotel registration"
  subCards:
   -
    title: ""
    links:
     - {link: "https://www.maldronhotelgalway.com/contact/", text: "Maldron Hotel Galway"}

# Hackathon (actually decorum)
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block (actually decorum)
aboutHackathonTitle: "Code of Conduct"
hackathonRows:
 - {title: "Please respect each other", image: "inclusion.png", details: "The Irish Computational Biology and Genomics Symposium is dedicated to facilitate the communication and presentation of research in a harassment-free environment. Any harassment on the basis of sex, gender, religion, sexual orientation, age, disability, nationality, or ethnicity will not be tolerated. Any actions such as stalking, assault, and disruptions to talks will not be tolerated. Any members violating the Code of Conduct will be expelled from the conference. Harassment includes any written, verbal, or physical actions that target any individuals on the bases outlined above or that cause harm to and/or degrade any individuals. If you are being harassed or notice anyone being harassed, please notify one of the members of the organizing committee. If you are found to not be compliant, you will be asked to comply with the code of conduct or barred from the conference. ICBG is intended to be an enjoyable and safe experience for everyone, and we expect all attendees of the conference to follow the code of conduct accordingly."}



# Sponsors
sponsorsTitle: "Sponsors"
enableSponsors: true

# Sponsors About Block
aboutSponsorsTitle: "Meet our Sponsors"
sposorsRows:
 - {title: "BioSciences", image: "hackathon-2.png", details: "From the outset, Bio-Sciences' business objective was to focus on becoming a market leader in the sales, service and distribution of laboratory equipment, reagents and consumables within the Biotechnology sector. More recently with the evolution of Molecular Diagnostics, technology has brought us into the Clinical Diagnostics market."}
 - {title: "The Ireland Funds", image: "theirelandfunds.png", details: "The Ireland Funds is a global philanthropic network established in 1976 to promote and support peace, culture, education and community development throughout the island of Ireland, and Irish-related causes around the world. With chapters in 12 countries,The Ireland Funds has raised over $600 million for deserving causes in Ireland and beyond, benefiting more than 3,200 different organizations."}
 - {title: "Macrogen", image: "macrogen.png", details: "Macrogen is a leading provider of DNA sequencing services, offering fast, high-quality Sanger and next generation sequencing for research and industry."}
 - {title: "RStudio", image: "rstudio.png", details: "RStudio is dedicated to sustainable investment in free and open-source software for data science."}
 - {title: "Systems Biology Ireland", image: "ucd.png", details: "Systems Biology Ireland investigates new therapeutic approaches to disease, with a focus on cancer at a systems level. We use a combination of traditional wet-lab and computational modeling approaches to understand cellular signaling networks."}


# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
